### ISSUE TITLE
Abomination event bugs

### ISSUE THREAD

**Issue by Meltup** [Taranchuk/Mo-Events#1]
I have been testing Mo'Events (Reupload https://steamcommunity.com/linkfilter/?url=https://github.com/Taranchuk/Mo-Events) and it seems that Abomination event is heavy bugged:

1. Abomination textures are not updated properly (it constantly faces only one direction regardless of movement and that direction is updated only upon attack);

2. I periodically get red errors in dev console when abominations attack: "MO_AbominationRace955594 started 10 jobs in 10 ticks." Sometimes this error leads to abominations stopping their attacks completely;

3. Abominations seem to not be recognized as a threat by NPCs. Trade caravan and requested military aid NPCs do not target them unless struck in melee combat (and melee combat seems to provoke only NPC that was hit. So NPCs go down just one by one).

4. Not sure if it is a bug but if wounded pawn from event gets up and walks out of the map before turning into Abomination then, after turning into Abomination, they reappear back on the edge of the map.

**Comment by Taranchuk** [comment]
1. fixed
3. made them permanent hostile faction and caravans shoot at them if they is closer 
2. and 4. not sure how to reproduce and how to fix them. Do you have a save from vanilla and mo-event mod with these errors?

**Comment by Meltup** [comment]
Was testing new build today, I can't seem to reproduce exactly the same "MO_AbominationRace955594 started 10 jobs in 10 ticks." error in 2, however there are now new errors in dev console when Abominations attack. Uploaded a screenshot with errors and save file (Vanilla Rimworld + Royalty):
https://github.com/Meltup/Mo-Events-testing

To reproduce 4:
- spawn the event;
- go to dev console;
- use heal random injury (10) multiple times on event pawn until they are up. It is possible to do with colonists but a pain;
- watch event pawn to walk out of the map;
- wait till message about event pawn turning into Abomination;
- observe that Abomination has spawned on the edge of the map.
I am not sure that it is a bug, however it is strange that mindless abomination returns back to player's colony tile after its host walked out.

**Comment by Taranchuk** [comment]
Fixed the jobdrivers errors.
Pre-abominations no longer leave the map.
